# Generated by Django 6.0.1 on 2026-01-30 17:02

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('color', models.CharField(max_length=64, unique=True)),
                ('color_code', models.CharField(max_length=7)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('country', models.CharField(max_length=64, unique=True)),
                ('flag', models.ImageField(upload_to='cars/country', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'jpg', 'png', 'heic', 'heif'])])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Marka',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('marka', models.CharField(max_length=64, unique=True)),
                ('photo', models.ImageField(upload_to='cars/marka', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'heic', 'heif'])])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('year', models.PositiveSmallIntegerField()),
                ('milage', models.PositiveIntegerField()),
                ('displacement', models.DecimalField(decimal_places=1, max_digits=2)),
                ('power', models.PositiveSmallIntegerField()),
                ('drive_type', models.CharField(choices=[('FWD', 'Front-Wheel Drive'), ('RWD', 'Rear-Wheel Drive'), ('AWD', 'All-Wheel Drive')], max_length=3)),
                ('transmission_type', models.CharField(choices=[('MT', 'Manual Transmission'), ('AT', 'Automatic Transmission')], default='MT', max_length=2)),
                ('doors_count', models.PositiveSmallIntegerField(choices=[(2, '2 doors'), (3, '3 doors'), (4, '4 doors'), (5, '5 doors')])),
                ('description', models.TextField(max_length=1200)),
                ('body', models.CharField(choices=[('sedan', 'Sedan'), ('hatchback', 'Hatchback'), ('suv', 'SUV'), ('crossover', 'Crossover'), ('coupe', 'Coupe'), ('convertible', 'Convertible'), ('wagon', 'Wagon'), ('pickup', 'Pickup'), ('minivan', 'Minivan')])),
                ('condition', models.CharField(choices=[('new', 'Yangi'), ('excellent', "A'lo"), ('good', 'Yaxshi'), ('fair', "O'rtacha"), ('poor', 'Yomon'), ('damaged', 'Shikastlangan')], default='good', max_length=10)),
                ('availability', models.CharField(choices=[('in_stock', 'Mavjud'), ('on_order', "Buyurtma bo'yicha"), ('sold', 'Sotilgan'), ('reserved', 'Band qilingan')], max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL)),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cars.carmodel')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cars.color')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cars.country')),
                ('fuel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cars.fuel')),
                ('marka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cars.marka')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='cars/cars', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'jpg', 'png', 'heic', 'heif'])])),
                ('is_main', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cars.car')),
            ],
            options={
                'ordering': ['-is_main', 'order'],
            },
        ),
        migrations.AddField(
            model_name='carmodel',
            name='marka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='cars.marka'),
        ),
    ]
