# Generated by Django 6.0.1 on 2026-01-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('DF', 'Draft'), ('PD', 'Published')], default='DF', max_length=2),
        ),
        migrations.AlterField(
            model_name='color',
            name='color_code',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
