# Generated by Django 6.0.1 on 2026-02-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_like_avtotypemarka_avto_type_and_marka_unique_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
