# Generated by Django 6.0.1 on 2026-02-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletionStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold_on_youcar', models.IntegerField(default=0, verbose_name='YouCar da sotilgan')),
                ('sold_elsewhere', models.IntegerField(default=0, verbose_name='Boshqa joyda sotilgan')),
                ('other_reason', models.IntegerField(default=0, verbose_name='Boshqa sabab')),
            ],
        ),
    ]
