# Generated by Django 6.0.1 on 2026-03-13 00:14

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_deletionstatistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='cars/bannner', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'heic', 'heif'])])),
                ('subtitle', models.CharField(max_length=240)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='cars.car')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
