# Generated by Django 6.0.1 on 2026-03-03 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websoket', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='reveiver',
            new_name='receiver',
        ),
    ]
